format = """
$container\
$directory\
[](fg:#a3aed2 bg:#394260)\
$git_branch\
[](fg:#394260)\
\n$character"""

[directory]
style = "fg:#090c0c bg:#a3aed2"
format = "[ $path ]($style)"
truncation_length = 0
truncation_symbol = "…/"
truncate_to_repo = false

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'